const RANKS = {
    admin:{
        id: "admin",
        nume: "Administrateur",
        weight: 1
    },
    rsdf:{
        id: "rsdf",
        nume: "Rédacteur-en-chef Dialogues francophones",
        weight: 2
    },
    redresdf:{
        id: "redresdf",
        nume: "Rédacteur responsable Dialogues francophones",
        weight: 3
    },
    redresaf:{
        id: "redresaf",
        nume: "Rédacteur responsable Agapes francophones",
        weight: 3
    },
    mcaf:{
        id: "mcaf",
        nume: "Membre comité de rédaction Agapes francophones",
        weight: 4
    },
    mcdf:{
        id: "mcdf",
        nume: "Membre comité de rédaction Dialogues francophones",
        weight: 4
    },
    evdf:{
        id: "evdf",
        nume: "Évaluateur Dialogues francophones",
        weight: 5
    },
    evaf:{
        id: "evaf",
        nume: "Évaluateur Agapes francophones",
        weight: 5
    },
    adf:{
        id: "adf",
        nume: "Auteur Dialogues francophones",
        weight: 6
    },
    aaf:{
        id: "aaf",
        nume: "Auteur Agapes francophones",
        weight: 6
    }
}

const LoginSignupErrors = {
    1: "Mot de passe trop court",
    2: "Mot de passe incorrect. Veuillez réessayer",
    3: "Désolé, nous ne reconnaissons pas cette adresse mail",
    4: "Désolé, il existe déjà un compte avec cette adresse mail",
    5: "Données incorrectes. Veuillez réessayer"
}

const CONTRIBUTION_STATUS = {
    1: "L’article a été envoyé",
    2: "L’article a été assigne aux évaluateurs",
    3: "L’article a été évalué par un évaluateur",
    4: "L’article a été évalué par deux évaluateurs",
    5: "Le processus d’évaluation est terminé"
}

const GeneralErrors = {
    "not-authorized":"Vous n’êtes pas autorisé pour cette action.",
    "doesnt-exist":"Cette proposition d’article n’existe pas",
    "not-completed":"Cette proposition d’article n’est pas encore évaluée"
}

const ProfileErrors = {
    "no-contrib-prop": "Aucune proposition de contribution",
    "no-art-eval":"Aucun article évalué",
    "no-art-to-eval":"Aucun article à évaluer",
    "no-art-to-assign":"Aucun article à assigner",
    "no-wip-art":"Aucun article en traitement",
    "no-art-finalized":"Aucun article finalisé"

}

const FormEnds = {
    "eval-df":"La rédaction de la revue Dialogues francophones vous remercie d’avoir accepté d’évaluer cet article.",
    "eval-af":"Le comité de rédaction du volume Agapes francophones vous remercie d’avoir accepté d’évaluer cet article.",
    "cieft":"Merci de votre proposition de communication. Vous serez contacté.e par le, la secrétaire du colloque.",
    "prop":"Votre formulaire a été transmis."
}

const RIGHTS =  {
    "admin":{
        "to-eval": false,
        "change-ranks": true,
        "change-to-rsdf": true,
        "change-to-redresdf": true,
        "change-to-redresaf": true,
        "change-to-mcdf": true,
        "change-to-mcaf": true,
        "change-to-evdf": true,
        "change-to-evaf": true,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": true,
        "af-articole-assign-panel": true,
        "df-contributii-wip-panel": true,
        "af-contributii-wip-panel": true,
        "df-contributii-finalizate-panel": true,
        "af-contributii-finalizate-panel": true,
        "access-cieft-page": true,
        "access-contrib-page-df": true,
        "access-contrib-page-af":true,
        "access-members-page": true,
        "access-eval-pages": false,
        "df-access-contributii-page": true,
        "af-access-contributii-page": true,
        "edit-view-logs":true
    },
    "rsdf":{
        "to-eval": false,
        "change-ranks": true,
        "change-to-rsdf": false,
        "change-to-redresdf": true,
        "change-to-redresaf": false,
        "change-to-mcdf": true,
        "change-to-mcaf": false,
        "change-to-evdf": true,
        "change-to-evaf": false,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": true,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": true,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": true,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": true,
        "access-contrib-page-df": true,
        "access-contrib-page-af":false,
        "access-members-page": true,
        "access-eval-pages": true,
        "df-access-contributii-page": true,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    },
    "redresdf": {
        "to-eval": false,
        "change-ranks": true,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": true,
        "change-to-mcaf": false,
        "change-to-evdf": true,
        "change-to-evaf": false,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": true,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": true,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": true,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": true,
        "access-contrib-page-df": true,
        "access-contrib-page-af":false,
        "access-members-page": true,
        "access-eval-pages": true,
        "df-access-contributii-page": true,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    },
    "redresaf":{
        "to-eval": false,
        "change-ranks": true,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": false,
        "change-to-mcaf": true,
        "change-to-evdf": false,
        "change-to-evaf": true,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": false,
        "af-articole-assign-panel": true,
        "df-contributii-wip-panel": false,
        "af-contributii-wip-panel": true,
        "df-contributii-finalizate-panel": false,
        "af-contributii-finalizate-panel": true,
        "access-cieft-page": true,
        "access-contrib-page-df": false,
        "access-contrib-page-af":true,
        "access-members-page": true,
        "access-eval-pages": true,
        "df-access-contributii-page": false,
        "af-access-contributii-page": true,
        "edit-view-logs":false
    },
    "mcdf":{
        "to-eval": false,
        "change-ranks": true,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": false,
        "change-to-mcaf": false,
        "change-to-evdf": true,
        "change-to-evaf": false,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": false,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": false,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": false,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": false,
        "access-contrib-page-df": true,
        "access-contrib-page-af":false,
        "access-members-page": true,
        "access-eval-pages": false,
        "df-access-contributii-page": false,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    },
    "mcaf":{
        "to-eval": false,
        "change-ranks": true,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": false,
        "change-to-mcaf": false,
        "change-to-evdf": false,
        "change-to-evaf": true,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": false,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": false,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": false,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": false,
        "access-contrib-page-df": false,
        "access-contrib-page-af":true,
        "access-members-page": true,
        "access-eval-pages": false,
        "df-access-contributii-page": false,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    },
    "evdf":{
        "to-eval": true,
        "change-ranks": false,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": false,
        "change-to-mcaf": false,
        "change-to-evdf": false,
        "change-to-evaf": false,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": true,
        "articole-de-evaluat-panel": true,
        "df-articole-assign-panel": false,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": false,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": false,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": false,
        "access-contrib-page-df": false,
        "access-contrib-page-af":false,
        "access-members-page": false,
        "access-eval-pages": false,
        "df-access-contributii-page": false,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    },
    "evaf":{
        "to-eval": true,
        "change-ranks": false,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": false,
        "change-to-mcaf": false,
        "change-to-evdf": false,
        "change-to-evaf": false,
        "contributii-propuse-panel": false,
        "articole-evaluate-panel": true,
        "articole-de-evaluat-panel": true,
        "df-articole-assign-panel": false,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": false,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": false,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": false,
        "access-contrib-page-df": false,
        "access-contrib-page-af":false,
        "access-members-page": false,
        "access-eval-pages": false,
        "df-access-contributii-page": false,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    },
    "aaf":{
        "to-eval": false,
        "change-ranks": false,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": false,
        "change-to-mcaf": false,
        "change-to-evdf": false,
        "change-to-evaf": false,
        "contributii-propuse-panel": true,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": false,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": false,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": false,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": false,
        "access-contrib-page-df": false,
        "access-contrib-page-af":false,
        "access-members-page": false,
        "access-eval-pages": false,
        "df-access-contributii-page": false,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    },
    "adf":{
        "to-eval": false,
        "change-ranks": false,
        "change-to-rsdf": false,
        "change-to-redresdf": false,
        "change-to-redresaf": false,
        "change-to-mcdf": false,
        "change-to-mcaf": false,
        "change-to-evdf": false,
        "change-to-evaf": false,
        "contributii-propuse-panel": true,
        "articole-evaluate-panel": false,
        "articole-de-evaluat-panel": false,
        "df-articole-assign-panel": false,
        "af-articole-assign-panel": false,
        "df-contributii-wip-panel": false,
        "af-contributii-wip-panel": false,
        "df-contributii-finalizate-panel": false,
        "af-contributii-finalizate-panel": false,
        "access-cieft-page": false,
        "access-contrib-page-df": false,
        "access-contrib-page-af":false,
        "access-members-page": false,
        "access-eval-pages": false,
        "df-access-contributii-page": false,
        "af-access-contributii-page": false,
        "edit-view-logs":false
    }
}

const months_short = {
    'Jan': 'January',
    'Feb':'February',
    'Mar':'March',
    'Apr':'April',
    'May':'May',
    'Jun':'June',
    'Jul':'July',
    'Aug':'August',
    'Sep':'September',
    'Oct':'October',
    'Nov':'November',
    'Dec':'December'
}

const months_num = {
    'January': 0 ,
    'February': 1,
    'March': 2,
    'April': 3,
    'May': 4,
    'June': 5,
    'July': 6,
    'August': 7,
    'September': 8,
    'October': 9,
    'November': 10,
    'December': 11
}

const days = [
    'Sun',
    'Mon',
    'Tue',
    'Wed',
    'Thu',
    'Fri',
    'Sat'
]