const RANKS = {
    0:"Administrator",
    101:"Redactor șef Dialogues Francophones",
    202:"Redactor responsabil Dialogues Francophones",
    303:"Redactor responsabil Agapes Francophones",
    404:"Membru în comitetul de redacție Agapes Francophones",
    505:"Membru în comitetul de redacție Dialogues Francophones",
    606:"Evaluator Dialogues Francophones",
    707:"Evaluator Agapes Francophones",
    808:"Autor Dialogues Francophones",
    909:"Autor Agapes Francophones",
    999:"Membru",
    1000:"Vizitator"
}

const LoginSignupErrors = {
    1: "Password is too short",
    2: "Passwords do not match",
    3: "Email address is not valid",
    4: "There already is an account with this email address",
    5: "Incorrect data. Try again"
}

//~~~~~~~~~~~~~~RIGHTS~~~~~~~~~~~~~~~
const RIGHTS = {
    0:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    101:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    202:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    303:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    404:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    505:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    606:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    707:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    808:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    909:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    },
    999:{
        'to-propose': false,
        'to-eval': false,
        'change-to-999': false,
        'change-to-909': false,
        'change-to-808': false,
        'change-to-707': false,
        'change-to-606': false,
        'change-to-505': false,
        'change-to-404': false,
        'change-to-303': false,
        'change-to-202': false,
        'change-to-101': false,
        'view-DF-props': false,
        'view-AF-props': false,
        'assign-DF-props': false,
        'assign-AF-props': false
    }
}